'use client';
import { DragEvent, FormEvent, ReactNode, useMemo, useState } from 'react';

type DemoProps={projectId:string}; type Lead={id:number;name:string;source:string;note:string;stage:string;tasks:string[]};
const money=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
const accounts=[
 {id:1,name:'Horizonte Serviços',owner:'Marina Costa',spend:8420,imp:92100,clicks:3868,conv:61,cpl:138,target:150,roas:2.1,alert:'OK'},
 {id:2,name:'Aurora Consultoria',owner:'Rafael Nunes',spend:6210,imp:70400,clicks:2534,conv:42,cpl:148,target:130,roas:1.3,alert:'CPL acima'},
 {id:3,name:'Vértice Advocacia',owner:'Bianca Lima',spend:9750,imp:118900,clicks:4637,conv:81,cpl:120,target:140,roas:2.8,alert:'OK'}];
const Metric=({label,value}:{label:string;value:string})=><div className="demo-metric"><small>{label}</small><strong>{value}</strong></div>;
const Head=({title}:{title:string})=><div className="demo-head"><span>Demonstração interativa</span><strong>{title}</strong></div>;
const Table=({headers,rows}:{headers:string[];rows:ReactNode[][]})=><div className="rich-table"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,n)=><td key={n}>{c}</td>)}</tr>)}</tbody></table></div>;

export default function ProjectDemo({projectId}:DemoProps){
 if(projectId==='ads')return <Ads/>; if(projectId==='crm')return <Crm/>; if(projectId==='maju')return <Maju/>;
 if(projectId==='tracker')return <Tracker/>; if(projectId==='nina')return <Nina/>; if(projectId==='acrux')return <Acrux/>;
 if(projectId==='clipagem')return <Clipagem/>; if(projectId==='biblioteca')return <Biblioteca/>; if(projectId==='processual')return <Processual/>;
 if(projectId==='termos')return <Termos/>; return <Finance/>;
}

function Ads(){
 const [section,setSection]=useState('Dashboard'),[period,setPeriod]=useState('Mês atual'),[account,setAccount]=useState<(typeof accounts)[number]|null>(null),[tab,setTab]=useState('Visão da conta'),[query,setQuery]=useState(''),[sync,setSync]=useState('↻ Sincronizar'),[newName,setNewName]=useState('');
 const [campaigns,setCampaigns]=useState([{name:'Pesquisa · serviço prioritário',status:'Ativa',spend:'R$ 4.320',conv:'36'},{name:'Remarketing · retorno',status:'Ativa',spend:'R$ 2.180',conv:'17'}]);
 const filtered=accounts.filter(a=>a.name.toLowerCase().includes(query.toLowerCase()));
 return <div className="product-shell"><aside className="product-nav"><div className="product-brand">Guidoni<small>Operação de mídia</small></div>{['Dashboard','Alertas','Saldos','Tarefas'].map(x=><button className={!account&&section===x?'active':''} onClick={()=>{setAccount(null);setSection(x)}} key={x}>{x}</button>)}</aside><section className="product-main">
 {account?<><button className="text-action" onClick={()=>setAccount(null)}>← Visão geral</button><div className="module-title"><div><h3>{account.name}</h3><p>Google Ads · No ritmo · 82%</p></div><span>Responsável: {account.owner}</span></div><div className="module-tabs">{['Visão da conta','Campanhas','Termos','Palavras-chave','Meta','Nova campanha','Relatório'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>
 {tab==='Visão da conta'&&<><div className="demo-metrics four"><Metric label="Investido" value={money(account.spend)}/><Metric label="Impressões" value={account.imp.toLocaleString('pt-BR')}/><Metric label="Cliques" value={account.clicks.toLocaleString('pt-BR')}/><Metric label="Conversões" value={`${account.conv}`}/></div><div className="demo-metrics four second"><Metric label="CPL" value={money(account.cpl)}/><Metric label="ROAS" value={`${account.roas}x`}/><Metric label="Receita" value="R$ 14.200"/><Metric label="Pacing" value="82%"/></div></>}
 {tab==='Campanhas'&&<Table headers={['Campanha','Status','Investido','Conversões','Ação']} rows={campaigns.map((c,i)=>[c.name,c.status,c.spend,c.conv,<button className="text-action" key={c.name} onClick={()=>setCampaigns(campaigns.map((x,n)=>n===i?{...x,status:x.status==='Ativa'?'Pausada':'Ativa'}:x))}>{c.status==='Ativa'?'Pausar':'Ativar'}</button>])}/>}
 {tab==='Meta'&&<><p className="module-copy">Facebook e Instagram: mídia paga e conteúdo orgânico reunidos no mesmo relatório.</p><div className="demo-metrics four"><Metric label="Investido" value="R$ 3.100"/><Metric label="Impressões" value="114.860"/><Metric label="Cliques" value="2.984"/><Metric label="Leads" value="55"/></div><Table headers={['Plataforma','Gasto','Alcance','Impressões','Cliques','CPC']} rows={[["Facebook","R$ 1.860","42.500","58.300","1.456","R$ 1,28"],["Instagram","R$ 1.240","38.600","56.560","1.528","R$ 0,81"]]}/></>}
 {tab==='Nova campanha'&&<div className="project-form"><label>Nome<input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Pesquisa · serviço prioritário"/></label><label>Objetivo<select><option>Leads</option><option>Vendas</option></select></label><label>Orçamento diário<input type="number" placeholder="150"/></label><label>Lance<select><option>Maximizar conversões</option><option>Maximizar cliques</option></select></label><label className="wide">URL final<input placeholder="https://exemplo.com/landing"/></label><label className="wide">Palavras-chave<textarea placeholder="uma por linha"/></label><button onClick={()=>{if(newName){setCampaigns([{name:newName,status:'Pausada',spend:'R$ 0',conv:'0'},...campaigns]);setTab('Campanhas')}}}>Criar campanha pausada</button></div>}
 {['Termos','Palavras-chave','Relatório'].includes(tab)&&<Table headers={[tab,'Status','Origem']} rows={[[tab==='Relatório'?`Relatório ${period}`:'Item demonstrativo','Ativo','Dados fictícios']]}/>}</>:
 <><div className="module-title"><div><h3>{section==='Dashboard'?'Visão geral':section}</h3><p>{section==='Dashboard'?'Contas ordenadas por urgência — quem precisa de atenção fica no topo.':'Visão consolidada da operação.'}</p></div><button className="control-button" onClick={()=>{setSync('Sincronizando…');setTimeout(()=>setSync('✓ Sincronizado'),500)}}>{sync}</button></div>{section==='Dashboard'?<><div className="demo-controls">{['7 dias','30 dias','Mês atual','Mês anterior'].map(x=><button className={period===x?'active':''} onClick={()=>setPeriod(x)} key={x}>{x}</button>)}</div><div className="demo-metrics four"><Metric label="Investido" value="R$ 24.380"/><Metric label="Receita" value="R$ 41.600"/><Metric label="Conversões" value="184"/><Metric label="Contas com alerta" value="2"/></div><div className="table-toolbar"><strong>Todas as contas ({filtered.length})</strong><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar conta…"/></div><Table headers={['Conta','Status','Responsável','Pacing','Investido','CTR','Conversões','CPL/alvo','ROAS','Alertas']} rows={filtered.map(a=>[<button className="open-row" key={a.id} onClick={()=>{setAccount(a);setTab('Visão da conta')}}>{a.name}</button>,'Ativa',a.owner,'No ritmo · 82%',money(a.spend),`${(a.clicks/a.imp*100).toFixed(1)}%`,`${a.conv}`,`${money(a.cpl)} / ${money(a.target)}`,`${a.roas}x`,a.alert])}/></>:<Table headers={['Conta',section==='Alertas'?'Alerta':section==='Saldos'?'Saldo':'Tarefa','Ação']} rows={accounts.map(a=>[a.name,section==='Alertas'?a.alert:section==='Saldos'?money(a.spend*.8):'Otimização semanal',<button className="text-action" key={a.id} onClick={()=>setAccount(a)}>Abrir conta</button>])}/>}</>}
 </section></div>;
}

function Crm(){
 const stages=['Contato','Desqualificado','Em conversa','Proposta','Fechado']; const [leads,setLeads]=useState<Lead[]>([{id:1,name:'Marina Alves',source:'Google Ads',note:'Retornar contato amanhã',stage:'Contato',tasks:[]},{id:2,name:'Rafael Nunes',source:'Google Ads',note:'Aguardando documentação',stage:'Em conversa',tasks:['Revisar documentos']},{id:3,name:'Bianca Lima',source:'Meta Ads',note:'Proposta enviada',stage:'Proposta',tasks:[]},{id:4,name:'Paulo Mendes',source:'Google',note:'Fora do perfil',stage:'Desqualificado',tasks:[]}]); const [archived,setArchived]=useState<Lead[]>([]),[showArchived,setShowArchived]=useState(false),[query,setQuery]=useState(''),[selected,setSelected]=useState<Lead|null>(null),[task,setTask]=useState('');
 const move=(id:number,stage:string)=>setLeads(leads.map(l=>l.id===id?{...l,stage}:l)); const resolve=(l:Lead)=>{setArchived([...archived,l]);setLeads(leads.filter(x=>x.id!==l.id));setSelected(null)}; const list=(showArchived?archived:leads).filter(l=>l.name.toLowerCase().includes(query.toLowerCase()));
 return <div className="crm-demo"><div className="crm-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar leads…"/><div><button className={!showArchived?'active':''} onClick={()=>setShowArchived(false)}>Ativos</button><button className={showArchived?'active':''} onClick={()=>setShowArchived(true)}>Arquivados ({archived.length})</button></div></div><div className="crm-board">{stages.map(stage=><section onDragOver={e=>e.preventDefault()} onDrop={e=>move(Number(e.dataTransfer.getData('lead')),stage)} key={stage}><header><span>{stage}</span><b>{list.filter(l=>l.stage===stage).length}</b></header>{list.filter(l=>l.stage===stage).map(l=><article draggable={!showArchived} onDragStart={(e:DragEvent)=>e.dataTransfer.setData('lead',`${l.id}`)} onClick={()=>setSelected(l)} key={l.id}><strong>{l.name}</strong><small>◷ 24/08/2026 · ☎ (11) 99999-0000</small><small>Fonte: {l.source}</small>{l.note&&<p>{l.note}</p>}<div><button onClick={e=>{e.stopPropagation();setSelected(l)}}>＋</button><button onClick={e=>{e.stopPropagation();resolve(l)}}>✓</button></div></article>)}</section>)}</div>{selected&&<div className="crm-modal" onClick={()=>setSelected(null)}><form onClick={e=>e.stopPropagation()} onSubmit={e=>e.preventDefault()}><button className="modal-close" onClick={()=>setSelected(null)}>×</button><h3>{selected.name}</h3><div className="lead-facts"><span><small>DATA</small>24/08/2026 14:32</span><span><small>FONTE</small>{selected.source}</span></div><label>Contato<select value={selected.stage} onChange={e=>{move(selected.id,e.target.value);setSelected({...selected,stage:e.target.value})}}>{stages.map(s=><option key={s}>{s}</option>)}</select></label><label>Observação<textarea defaultValue={selected.note}/></label><h4>Tarefas</h4>{selected.tasks.map(t=><p className="task-item" key={t}>✓ {t}</p>)}<div className="task-create"><input value={task} onChange={e=>setTask(e.target.value)} placeholder="Nova tarefa"/><input type="date"/><button onClick={()=>{if(task){const u={...selected,tasks:[...selected.tasks,task]};setLeads(leads.map(l=>l.id===u.id?u:l));setSelected(u);setTask('')}}}>＋ Adicionar</button></div><footer><button onClick={()=>resolve(selected)}>✓ Marcar como resolvido</button><button className="primary" onClick={()=>setSelected(null)}>Salvar</button></footer></form></div>}</div>;
}

function Maju(){const [messages,setMessages]=useState<{text:string;mine?:boolean}[]>([{text:'Olá, preciso entender se tenho direito a uma revisão.',mine:true}]),[input,setInput]=useState(''),[step,setStep]=useState(0);const replies=['Olá! Posso fazer algumas perguntas para entender melhor o seu caso?','Esse assunto envolve benefício, contrato, família ou trabalho?','Perfeito. Organizei as informações e vou encaminhar para análise da equipe.'];const send=(e:FormEvent)=>{e.preventDefault();if(input){setMessages([...messages,{text:input,mine:true},{text:replies[Math.min(step,2)]}]);setInput('');setStep(step+1)}};return <div className="maju-demo"><Head title="Atendimento demonstrativo"/><p className="module-copy">Atendimento controlado por estados, regras e limites antes do encaminhamento.</p><div className="architecture"><b>Arquitetura confirmada</b><span>n8n → API oficial da Meta → Chatwoot → Google Sheets + SQL · VPS</span></div><div className="phone-demo"><header>Maju · atendimento <i>online</i></header><div>{messages.map((m,i)=><p className={m.mine?'mine':''} key={i}>{m.text}</p>)}</div><form onSubmit={send}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Digite uma resposta…"/><button>Enviar</button></form></div></div>}
function Tracker(){const nodes=['Anúncio','Landing page','Clique WhatsApp','Conversa','CRM','Conversão offline'];const [done,setDone]=useState(-1),[running,setRunning]=useState(false),[utm,setUtm]=useState('utm_source=google&utm_campaign=servico&gclid=demo-8f2a');const run=async()=>{setRunning(true);setDone(-1);for(let i=0;i<nodes.length;i++){setDone(i);await new Promise(r=>setTimeout(r,300))}setRunning(false)};return <div className="inline-demo"><Head title="Rastreamento de origem"/><label className="wide-input">Parâmetros do clique<input value={utm} onChange={e=>setUtm(e.target.value)}/></label><div className="tracker-flow">{nodes.map((n,i)=><span className={done>=i?'active':''} key={n}>{n}</span>)}</div><button className="demo-primary" disabled={running||!utm} onClick={run}>{running?'Registrando…':'Simular clique completo'}</button><p className="demo-result">{done<0?'Nenhum evento iniciado.':done===5?'✓ Origem enviada às plataformas.':`${nodes[done]} registrado.`}</p></div>}
function Nina(){const [topic,setTopic]=useState(''),[lang,setLang]=useState('PT-BR'),[generated,setGenerated]=useState(false);return <div className="inline-demo"><Head title="Mesa editorial da Nina"/><div className="editor-layout"><aside><strong>Pautas disponíveis</strong>{['Mudança regulatória','Decisão relevante','Tendência de mercado'].map(t=><button className={topic===t?'active':''} onClick={()=>{setTopic(t);setGenerated(false)}} key={t}>{t}</button>)}<select value={lang} onChange={e=>setLang(e.target.value)}><option>PT-BR</option><option>EN</option></select></aside><article><small>Rascunho · {lang}</small><h3>{generated?topic:'Escolha uma pauta'}</h3>{generated?<><p><b>Contexto.</b> O tema altera uma prática acompanhada pelo público.</p><p><b>Efeito prático.</b> A análise identifica quem é afetado e o que muda.</p><p><b>Ponto crítico.</b> Fontes, interesses e limites ficam visíveis.</p></>:<p>A demonstração montará contexto, efeitos práticos e ponto de atenção.</p>}</article></div><button className="demo-primary" disabled={!topic} onClick={()=>setGenerated(true)}>Gerar estrutura</button></div>}
function Acrux(){const steps=['Coleta de fontes','Eventos','Curadoria','Pacote para a Nina'];const [progress,setProgress]=useState(0);return <div className="inline-demo"><Head title="Sessão de curadoria Acrux"/><div className="pipeline rich">{steps.map((s,i)=><span className={progress>i?'done':progress===i?'current':''} key={s}><b>0{i+1}</b>{s}<small>{progress>i?'concluído':progress===i?'próximo':'aguardando'}</small></span>)}</div><button className="demo-primary" onClick={()=>setProgress(progress>=4?0:progress+1)}>{progress>=4?'Reiniciar':'Executar próxima etapa'}</button><p className="demo-result">{progress>=4?'✓ Pacote pronto para a Nina.':`${progress} de 4 etapas concluídas.`}</p></div>}
function Clipagem(){const items=[['24/08/2026','Trabalhista','Alta','TST','Tribunal consolida novo entendimento sobre jornada'],['23/08/2026','Empresarial','Média','JOTA','Mercado de capitais ganha discussão regulatória'],['22/08/2026','Civil','Alta','Migalhas','Tribunal define critérios para publicidade infantil'],['21/08/2026','Geral','Média','CNJ','Jornada debate acesso à Justiça']];const [q,setQ]=useState(''),[area,setArea]=useState('Todas'),[selected,setSelected]=useState('');const list=items.filter(x=>(area==='Todas'||x[1]===area)&&x.join(' ').toLowerCase().includes(q.toLowerCase()));return <div className="inline-demo"><Head title="Dashboard de clipping jurídico"/><div className="filter-row"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Título, resumo ou fonte…"/><select value={area} onChange={e=>setArea(e.target.value)}><option>Todas</option><option>Trabalhista</option><option>Empresarial</option><option>Civil</option><option>Geral</option></select><span>{list.length} matérias</span></div><Table headers={['Data','Área','Relevância','Fonte','Título']} rows={list.map(x=>[x[0],x[1],x[2],x[3],<button className="open-row" key={x[4]} onClick={()=>setSelected(x[4])}>{x[4]}</button>])}/><p className="demo-result">{selected?`${selected} — aberta para curadoria.`:'Selecione uma matéria.'}</p></div>}
function Biblioteca(){const [url,setUrl]=useState(''),[filter,setFilter]=useState('Todos'),[status,setStatus]=useState('Atualização semanal ativa.');const cards=[['Abertura editorial','Landing pages'],['Prova em números','Conversão'],['Serviços em sequência','Institucional'],['Linha do tempo','Conteúdo'],['Chamada lateral','Conversão'],['Comparativo','Apresentação']];return <div className="inline-demo"><Head title="Biblioteca visual viva"/><div className="reference-bar"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://site-de-referencia.com"/><button onClick={()=>setStatus(url?'✓ Tipografia, cards, botões e composição adicionados.':'Informe um endereço.')}>Adicionar referência</button></div><div className="demo-controls">{['Todos','Conversão','Conteúdo','Landing pages'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="pattern-grid">{cards.filter(x=>filter==='Todos'||x[1]===filter).map((x,i)=><button onClick={()=>setStatus(`${x[0]} selecionado para reutilização.`)} key={x[0]}><i className={`pattern pattern-${i}`}/><strong>{x[0]}</strong><small>{x[1]}</small></button>)}</div><p className="demo-result">{status}</p></div>}
function Processual(){const [events,setEvents]=useState(['Distribuição registrada · 12/08','Documento juntado · 15/08','Prazo identificado · 18/08']);return <div className="inline-demo"><Head title="Monitor processual"/><select><option>Processo demonstrativo 001</option><option>Processo demonstrativo 002</option></select><div className="process-timeline">{events.map((x,i)=><div key={i}><b>{x.split(' · ')[0]}</b><span>{x.split(' · ')[1]} · responsável notificado.</span></div>)}</div><button className="demo-primary" onClick={()=>setEvents([...events,'Nova movimentação encontrada · hoje'])}>Verificar atualização no DataJud</button></div>}
function Termos(){const [text,setText]=useState('curso gratuito\nmodelo de currículo\nserviço especializado\norçamento personalizado'),[analyzed,setAnalyzed]=useState(false);const decisions=useMemo(()=>text.split('\n').filter(Boolean).map(t=>[t,/gratuito|currículo|vaga/i.test(t)?'Negativar':'Manter',/gratuito|currículo|vaga/i.test(t)?'Intenção incompatível':'Potencial comercial']),[text]);return <div className="inline-demo"><Head title="Limpador inteligente de termos"/><div className="terms-layout"><label>Termos de pesquisa<textarea value={text} onChange={e=>{setText(e.target.value);setAnalyzed(false)}}/></label>{analyzed?<Table headers={['Termo','Decisão','Motivo']} rows={decisions}/>:<div className="empty-analysis">Aguardando análise em duas passagens.</div>}</div><button className="demo-primary" onClick={()=>setAnalyzed(true)}>Analisar com IA</button></div>}
function Finance(){const [period,setPeriod]=useState('Este mês');const factor=period==='Este mês'?1:period==='Mês anterior'?.72:2.8;return <div className="inline-demo"><Head title="Visão financeira pessoal"/><div className="demo-controls">{['Este mês','Mês anterior','Trimestre'].map(x=><button className={period===x?'active':''} onClick={()=>setPeriod(x)} key={x}>{x}</button>)}</div><div className="demo-metrics four"><Metric label="Receitas" value={money(18400*factor)}/><Metric label="Despesas" value={money(10430*factor)}/><Metric label="Resultado" value={money(7970*factor)}/><Metric label="Poupança" value="43%"/></div><div className="finance-chart"><b>Fluxo de caixa</b>{[35,62,48,80,67,92,76].map((x,i)=><i style={{height:`${x}%`}} key={i}/>)}</div><Table headers={['Lançamento','Tipo','Valor']} rows={[["Receita de serviços","Entrada",money(18400*factor)],["Ferramentas e mídia","Saída",money(4280*factor)],["Operação","Saída",money(6150*factor)]]}/></div>}
